services:
  mongodb:
    image: mongo:7
    container_name: MONGODB_CONTAINER
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: Neighbours
    volumes:
      - mongo_data:/data/db
    networks:
      - cn_network

  neo4j:
    image: neo4j:5
    container_name: NEO4J_CONTAINER
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/neo4jadmin
    
    volumes:
      - neo4j_data:/data
    networks:
      - cn_network

  postgres:
    image: postgres:16
    container_name: POSTGRES_CONTAINER
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: connected_neighbours
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cn_network

volumes:
  mongo_data:
  neo4j_data:
  postgres_data:

networks:
  cn_network:
    driver: bridge