// Catalogue fixe de centres d'intérêt, PARTAGÉ entre le profil de l'habitant
// (PUT /me/interets) et la création d'événement (interests -> tags Neo4j).
// Valeurs en minuscules, entre 2 et 30 caractères (ce que le backend valide).
export const CATALOGUE_INTERETS = [
  // loisirs & culture
  'sport',
  'musique',
  'danse',
  'théâtre',
  'cinéma',
  'séries',
  'lecture',
  'écriture',
  'poésie',
  'bande dessinée',
  'manga',
  'art',
  'peinture',
  'dessin',
  'photographie',
  'artisanat',
  'couture',
  'tricot',
  'poterie',
  'collection',
  // maison & bricolage
  'bricolage',
  'menuiserie',
  'mécanique',
  'décoration',
  'jardinage',
  'potager',
  'permaculture',
  // cuisine
  'cuisine',
  'pâtisserie',
  'boulangerie',
  'œnologie',
  'café',
  // nature & sport
  'nature',
  'randonnée',
  'vélo',
  'course à pied',
  'natation',
  'yoga',
  'méditation',
  'fitness',
  'football',
  'basketball',
  'tennis',
  'escalade',
  'pêche',
  'camping',
  'plongée',
  'surf',
  'ski',
  'animaux',
  // savoir & tech
  'technologie',
  'informatique',
  'programmation',
  'robotique',
  'sciences',
  'astronomie',
  'histoire',
  'langues',
  'jeux vidéo',
  'jeux de société',
  'échecs',
  // sorties
  'voyage',
  'concerts',
  'festivals',
  'musées',
  'mode',
  // vie de quartier & entraide
  'bénévolat',
  'solidarité',
  'entraide',
  'voisinage',
  'écologie',
  'recyclage',
  'compost',
  'famille',
  'enfants',
  'seniors',
  'éducation',
  'soutien scolaire',
  'covoiturage',
  'santé',
  'spiritualité',
  'débat',
  'actualités',
  'entrepreneuriat',
  'finance',
] as const;
